[package]
name = "suomipelit-lobby"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.6.2", features = ["ws"] }
rand = "0.8.5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1.24.1", features = ["full"] }
